let num1 = 8;
let num2 = 4;
let soma = num1 + num2;
console.log(soma);
let subtracao = num1 - num2;
console.log(subtracao);
let multiplicacao = num1 * num2;
console.log(multiplicacao);
let divisao = num1 / num2;
console.log(divisao);
